### ISSUE TITLE
V1 Case needs a power slide button

### ISSUE THREAD

**Issue by 57Bravo** [sqfmi/beepy-hardware#17]
When doing development on the keyboard, I'm constantly sliding the power button on / off with the V1 case. I have to use a small screwdriver because the switch is tiny. 

It would be nice it the V1 case had a small slide button so you could use your finger instead.

**Comment by 57Bravo** [comment]
FW updates now allow upper right button to gracefully power and shutdown rpi without sliding switch.

**Comment by prokrypt** [comment]
I use the corner of a usb-c plug to toggle the switch.

**Comment by 57Bravo** [comment]
If you update the keyboard firmware and associated kernel module, the upper right hand button allows for digital power up/down. They also exposed the led to sysfs, so you can control it without unloading the keyboard kernel module to hit I2C directly.

**Comment by prokrypt** [comment]
My switch does soft shutdown too, somehow...
![IMG_20230917_144246099](https://github.com/sqfmi/beepy-hardware/assets/1832555/c5bfce39-77d5-47dd-8618-55dc56ed1570)

**Comment by 57Bravo** [comment]
Mod city ha. Here's mine https://github.com/57Bravo/BeepSensors
