### ISSUE TITLE
Slim case — Lower front two screw holes do not fit the screw part suggested

### ISSUE THREAD

**Issue by jogloran** [sqfmi/beepy-hardware#20]
Having printed the two halves of the slim case, the exact Amazon Torx-head screw part suggested by the README seem to spin freely in the bottom half of the case.

Is there any way we can get access to CAD files so that we can adjust the screw diameter of the holes?

**Comment by jogloran** [comment]
I'm closing this as I just noticed the .step files in there.

**Comment by a8ksh4** [comment]
There's a link to the cad model in Onshap in the readme, too.

**Comment by jogloran** [comment]
Thanks. I shrank the hole -- works like a charm now.
